#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf gzip-1.12.tar.xz
cd gzip-1.12
./configure --prefix=/usr --host=$LFS_TGT
make
make DESTDIR=$LFS install
cd $LFS/sources
rm -rf $LFS/sources/gzip-1.12
