#!/bin/bash -e
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf gzip-1.10.tar.xz
cd gzip-1.10
./configure --prefix=/usr --host=$LFS_TGT
make
make DESTDIR=$LFS install
 rm -rf $LFS/sources/gzip-1.10
