#!/bin/bash -e 
./prepare 
export MAKEFLAGS='-j2' 
cd $LFS/sources
tar -xvf sed-4.8.tar.xz
cd sed-4.8
./configure --prefix=/usr   \
            --host=$LFS_TGT
make
make DESTDIR=$LFS install
 rm -rf $LFS/sources/sed-4.8
