#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
#lsattr $LFS/usr
chattr -V -ais -R $LFS/{usr,lib,var,etc,bin,sbin,tools}
chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  *64) chown -R root:root $LFS/lib64 ;;
esac
mkdir -pv $LFS/{dev,proc,sys,run}
