#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
echo "SUCCESS"
chattr -ais -f -R $LFS/{usr,lib,var,etc,bin,sbin,tools} | true
chown -R root:root $LFS/{usr,lib,var,etc,bin,sbin,tools}
case $(uname -m) in
  *64) chown -R root:root $LFS/lib64 ;;
esac
mkdir -pv $LFS/{dev,proc,sys,run}
