#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
cd gcc-12.2.0
cd       build
make
make DESTDIR=$LFS install
rm $LFS/usr/bin/cc || true
ln -sv gcc $LFS/usr/bin/cc
cd $LFS/sources
rm -rf $LFS/sources/gcc-12.2.0
