#!/bin/bash 
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
cd gcc-11.2.0
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
 ;;
  ppc64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/rs6000/t-linux64
 ;;
  aarch64)
    sed -e '/mabi.lp64=/s/lib64/lib/' \
    -i.orig gcc/config/aarch64/t-aarch64-linux
 ;;
esac
case $(uname -m) in
  armv6l)
    patch -Np1 -i ../gcc-10.2.0-armv6.patch
 ;;
  armv7l)
    patch -Np1 -i ../gcc-10.2.0-armv7.patch
 ;;
  armv8l)
    patch -Np1 -i ../gcc-10.2.0-armv8.patch
 ;;
esac
cd       build
ln -s ../../../libgcc/gthr-posix.h $LFS_TGT/libgcc/gthr-default.h

../configure                                       \
    --build=$(../config.guess)                     \
    --host=$LFS_TGT                                \
    --prefix=/usr                                  \
    CC_FOR_TARGET=$LFS_TGT-gcc                     \
    --with-build-sysroot=$LFS                      \
    --enable-initfini-array                        \
    --disable-nls                                  \
    --disable-multilib                             \
    --disable-decimal-float                        \
    --disable-libatomic                            \
    --disable-libgomp                              \
    --disable-libquadmath                          \
    --disable-libssp                               \
    --disable-libvtv                               \
    --disable-libstdcxx                            \
    --enable-languages=c,c++

make

make DESTDIR=$LFS install

ln -sv gcc $LFS/usr/bin/cc

rm -rf $LFS/sources/gcc-11.2.0
