#!/bin/bash -e
set +h
umask 022
export LFS=/mnt/lfs
export LC_ALL=POSIX
case $(uname -m) in
    arm*) LFS_TGT=$(uname -m)-lfs-linux-gnueabihf ;;
    *) LFS_TGT=$(uname -m)-lfs-linux-gnu ;;
esac
export LFS_TGT
echo $(uname -m)-lfs-linux-gnu
echo $LFS_TGT
export PATH=/usr/bin
if [ ! -L /bin ]; then export PATH=/bin:$PATH; fi
export PATH=$LFS/tools/bin:$PATH
CONFIG_SITE=$LFS/usr/share/config.site
export CONFIG_SITE
export MAKEFLAGS='-j2'
