#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf nano-7.2.tar.xz
cd nano-7.2
./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --enable-utf8     \
            --docdir=/usr/share/doc/nano-7.2 &&
make
make install &&
install -v -m644 doc/{nano.html,sample.nanorc} /usr/share/doc/nano-7.2
cd $LFS/sources
rm -rf $LFS/sources/nano-7.2
