#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf libpipeline-1.5.6.tar.gz
cd libpipeline-1.5.6
./configure --prefix=/usr
make
make check
make install
cd /sources
rm -rf /sources/libpipeline-1.5.6
