#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf libpipeline-1.5.6.tar.gz
cd libpipeline-1.5.6
./configure --prefix=/usr
make
make check
make install
cd $LFS/sources
rm -rf $LFS/sources/libpipeline-1.5.6
