#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf automake-1.16.5.tar.xz
cd automake-1.16.5
./configure --prefix=/usr
make
make check
make install
cd $LFS/sources
rm -rf $LFS/sources/automake-1.16.5
