#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf procps-ng-4.0.0.tar.xz
cd procps-ng-4.0.0
./configure --prefix=/usr                            \
            --docdir=/usr/share/doc/procps-ng-4.0.0 \
            --disable-static                         \
            --disable-kill
make
make check
make install
cd $LFS/sources
rm -rf $LFS/sources/procps-ng-4.0.0
