#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf Python-3.11.4.tar.xz
cd Python-3.11.4
./configure --prefix=/usr   \
            --enable-shared \
            --without-ensurepip
make
make install
cd $LFS/sources
rm -rf $LFS/sources/Python-3.11.4
