#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf python-3.11.4-docs-html.tar.bz2
cd python-3.11.4-docs-html
./configure --prefix=/usr   \
            --enable-shared \
            --without-ensurepip
make
make install
cd $LFS/sources
rm -rf $LFS/sources/python-3.11.4-docs-html
