#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf bison-3.8.2.tar.xz
cd bison-3.8.2
./configure --prefix=/usr \
            --docdir=/usr/share/doc/bison-3.8.2
make
make install
cd /sources
rm /sources/bison-3.8.2
