#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf python-3.10.6-docs-html.tar.bz2
cd python-3.10.6-docs-html
./configure --prefix=/usr   \
            --enable-shared \
            --without-ensurepip
make
make install
cd /sources
rm -rf /sources/python-3.10.6-docs-html
