#!/bin/bash -e
set -e
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
rm -rf /usr/share/{info,man,doc}/*
find /usr/{lib,libexec} -name \*.la -delete
rm -rf /tools
exit
umount $LFS/dev/pts
umount $LFS/{sys,proc,run,dev}
cd $LFS
tar -cJpf $HOME/lfs-temp-tools-11.1.tar.xz .
