#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
cd glibc-2.35
cd       build
../configure --prefix=/usr                            \
             --disable-werror                         \
             --enable-kernel=3.2                      \
             --enable-stack-protector=strong          \
             --with-headers=/usr/include              \
             libc_cv_slibdir=/usr/lib
make
make check
