#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf acl-2.3.1.tar.xz
cd acl-2.3.1
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.2.6
make
make check
make install
cd /sources
rm -rf /sources/acl-2.3.1
