#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf zstd-1.5.2.tar.gz
cd zstd-1.5.2
make
make check
make prefix=/usr install
rm -v /usr/lib/libzstd.a
cd /sources
rm /sources/zstd-1.5.2
