#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf bc-6.0.1.tar.xz
cd bc-6.0.1
CC=gcc ./configure --prefix=/usr -G -O3 -r
make
make test
make install
cd /sources
rm -rf /sources/bc-6.0.1
