#!/bin/bash -e
set -e
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf acl-2.3.1.tar.xz
cd acl-2.3.1
./configure --prefix=/usr         \
            --disable-static      \
            --docdir=/usr/share/doc/acl-2.3.1
make
make install
