#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf psmisc-23.6.tar.xz
cd psmisc-23.6
./configure --prefix=/usr
make
make check
make install
cd $LFS/sources
rm -rf $LFS/sources/psmisc-23.6
