#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf less-643.tar.gz
cd less-643
./configure --prefix=/usr --sysconfdir=/etc
make
make check
make install
cd $LFS/sources
rm -rf $LFS/sources/less-643
