#!/bin/bash -e
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf expat-2.4.6.tar.xz
cd expat-2.4.6
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-2.4.6
make
make check
make install
install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.4.6
cd /sources
rm /sources/expat-2.4.6
