#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf groff-1.23.0.tar.gz
cd groff-1.23.0
PAGE=<paper_size> ./configure --prefix=/usr
make
make check
make install
cd $LFS/sources
rm -rf $LFS/sources/groff-1.23.0
