#!/bin/bash -e
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf binutils-2.38.tar.xz
cd binutils-2.38
mkdir -v build
cd       build
../configure --prefix=$LFS/tools \
             --with-sysroot=$LFS \
             --target=$LFS_TGT   \
             --disable-nls       \
             --disable-werror
 rm -rf $LFS/sources/binutils-2.38
