#!/bin/bash -e
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf gcc-11.2.0.tar.xz
cd gcc-11.2.0
tar -xf ../mpfr-4.1.0.tar.xz
mv -v mpfr-4.1.0 mpfr
tar -xf ../gmp-6.2.1.tar.xz
mv -v gmp-6.2.1 gmp
tar -xf ../mpc-1.2.1.tar.gz
mv -v mpc-1.2.1 mpc
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
 ;;
   ppc64le)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/rs6000/t-linux64
 ;;
  aarch64)
    sed -e '/mabi.lp64=/s/lib64/lib/' \
    -i.orig gcc/config/aarch64/t-aarch64-linux
 ;;
  mips64le)
    sed -e '/ma64=/s/lib64/lib/' \
    -i.orig gcc/config/mips/t-linux64
 ;;
esac
case $(uname -m) in
  armv6l)
    patch -Np1 -i ../gcc-10.2.0-armv6.patch
 ;;
  armv7l)
    patch -Np1 -i ../gcc-10.2.0-armv7.patch
 ;;
  aarch64)
    patch -Np1 -i ../gcc-10.2.0-armv8.patch
 ;;
esac
mkdir -v build
cd       build
../configure                  \
    --target=$LFS_TGT         \
    --prefix=$LFS/tools       \
    --with-glibc-version=2.35 \
    --with-sysroot=$LFS       \
    --with-newlib             \
    --without-headers         \
    --enable-initfini-array   \
    --disable-nls             \
    --disable-shared          \
    --disable-multilib        \
    --disable-decimal-float   \
    --disable-threads         \
    --disable-libatomic       \
    --disable-libgomp         \
    --disable-libquadmath     \
    --disable-libssp          \
    --disable-libvtv          \
    --disable-libstdcxx       \
    --enable-languages=c,c++
make
make install
cd ..
