#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf linux-6.4.12.tar.xz
cd linux-6.4.12
make mrproper
make headers
find usr/include -type f ! -name '*.h' -delete

cp -rv usr/include $LFS/usr
cd $LFS/sources
rm -rf $LFS/sources/linux-6.4.12
