#!/bin/bash -e
./prepare 
export MAKEFLAGS='-j2'
cd $LFS/sources
cd gcc-11.2.0
cd       build
make
make install
cd ..
cat gcc/limitx.h gcc/glimits.h gcc/limity.h > \
  `dirname $($LFS_TGT-gcc -print-libgcc-file-name)`/install-tools/include/limits.h
 rm -rf $LFS/sources/gcc-11.2.0
