#!/bin/bash
set -e
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf gcc-13.2.0.tar.xz
cd gcc-13.2.0
mkdir -v build
cd       build
../libstdc++-v3/configure           \
    --host=$LFS_TGT                 \
    --build=$(../config.guess)      \
    --prefix=/usr                   \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/13.2.0
make
make DESTDIR=$LFS install
ls $LFS/usr/lib/
rm -v $LFS/usr/lib/lib{stdc++,stdc++fs,supc++}.la
cd $LFS/sources
rm -rf $LFS/sources/gcc-13.2.0
