#!/bin/bash 
./prepare
export MAKEFLAGS='-j2'
cd $LFS/sources
tar -xvf linux-5.13.12.tar.xz
cd linux-5.13.12
make mrproper
make headers
find usr/include -name '.*' -delete
rm usr/include/Makefile
cp -rv usr/include $LFS/usr
 rm -rf $LFS/sources/linux-5.13.12
